# Generated by Django 5.0.4 on 2024-05-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('usuario', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=40)),
                ('pontuacao_total', models.IntegerField()),
            ],
        ),
    ]
