# Generated by Django 5.0.4 on 2024-05-31 00:24

from django.db import migrations

def insere_tema(apps, schema_editor):
    Tema = apps.get_model('palavra', 'Tema')
    Tema.objects.create(
        descricao='Geral'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('palavra', '0002_tema'),
    ]

    operations = [
        migrations.RunPython(insere_tema),
    ]
