# Generated by Django 5.0.4 on 2024-05-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palavra', '0003_palavra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='senha',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
