# Generated by Django 5.0.4 on 2024-05-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palavra', '0003_palavra'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='temp', max_length=25),
            preserve_default=False,
        ),
    ]
