# Generated by Django 5.0.4 on 2024-05-30 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palavra', '0004_usuario_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
    ]
