# Generated by Django 5.0.4 on 2024-06-06 23:38

from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    User = get_user_model()
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='admir',
            email='admir@example.com',
            password='supersecret'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('palavra', '0005_insere_palavras'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
