# Generated by Django 5.0.4 on 2024-05-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palavra', '0005_auto_20240527_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='senha',
            field=models.CharField(max_length=30),
        ),
    ]
