# Generated by Django 5.0.4 on 2024-05-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palavra', '0005_remove_usuario_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='foto.png', upload_to='foto_perfil/'),
            preserve_default=False,
        ),
    ]
