# Generated by Django 5.0.4 on 2024-06-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palavra', '0006_create_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavra',
            name='descricao',
            field=models.CharField(max_length=5),
        ),
    ]
